# Generated by Django 6.0.4 on 2026-05-01 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_users_id_alter_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jeepneys',
            fields=[
                ('jeep_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('max_capacity', models.IntegerField()),
                ('current_passenger', models.IntegerField()),
                ('status', models.CharField(choices=[('avail', 'Available'), ('in_trans', 'In Transit'), ('full', 'Full')], default='avail', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('UT-REG', 'Regular'), ('UT-STD', 'Student'), ('UT-SNR', 'Senior'), ('UT-PWD', 'PWD/Pregnant')], max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('route_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=50)),
                ('base_fare', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stop_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='jeepneys',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.routes'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='jeep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jeepneys'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.routes'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.passengers'),
        ),
    ]
