# Generated by Django 6.0.4 on 2026-05-01 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_jeepneys_passengers_routes_stops_tickets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=50)),
                ('base_fare', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='jeep',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='route',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='user',
        ),
        migrations.CreateModel(
            name='Jeepney',
            fields=[
                ('jeep_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('max_capacity', models.IntegerField()),
                ('current_passenger', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('avail', 'Available'), ('in_trans', 'In Transit'), ('full', 'Full')], default='avail', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.route')),
            ],
        ),
        migrations.RenameModel(
            old_name='Stops',
            new_name='Stop',
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.stop')),
            ],
        ),
        migrations.RenameModel(
            old_name='Passengers',
            new_name='Passenger',
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('jeep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jeepney')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.passenger')),
            ],
        ),
        migrations.DeleteModel(
            name='Jeepneys',
        ),
        migrations.DeleteModel(
            name='Routes',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
