# Generated by Django 6.0.4 on 2026-05-05 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.DecimalField(decimal_places=2, default=15.0, max_digits=6)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jeep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.jeepney')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.passenger')),
            ],
        ),
    ]
