# Generated by Django 6.0.4 on 2026-05-05 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=50)),
                ('base_fare', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jeepney',
            fields=[
                ('jeep_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('max_capacity', models.IntegerField()),
                ('current_passenger', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('avail', 'Available'), ('in_trans', 'In Transit'), ('full', 'Full')], default='avail', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.route')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.stop')),
            ],
        ),
    ]
